decision:
  gray_margin: 0.2
  heuristic_weight: 0.3
  keep_threshold: 0.45
  use_heuristics: true
language:
  default: auto
models:
  embed: text-embedding-3-small
  embed_dims: 1536
  fast: gpt-5-mini-2025-08-07
  main: gpt-5-2025-08-07
  provider: openai
paths:
  attachments: /Users/jose/Documents/Obsidian/Ever-preprocessed/attachments
  curated_attachments: /Users/jose/Documents/Obsidian/Ever-curated/attachments
  curated_notes: /Users/jose/Documents/Obsidian/Ever-curated/notes
  curated_vault: /Users/jose/Documents/Obsidian/Ever-curated
  out_assets: /Users/jose/Documents/Obsidian/Ever-curated/attachments
  out_notes: /Users/jose/Documents/Obsidian/Ever-curated/notes
  preprocessed_attachments: /Users/jose/Documents/Obsidian/Ever-preprocessed/attachments
  preprocessed_notes: /Users/jose/Documents/Obsidian/Ever-preprocessed/notes
  preprocessed_vault: /Users/jose/Documents/Obsidian/Ever-preprocessed
  raw_attachments: /Users/jose/Documents/Obsidian/Evermd/attachments
  raw_notes: /Users/jose/Documents/Obsidian/Evermd/notes
  raw_vault: /Users/jose/Documents/Obsidian/Evermd
  test_curated_attachments: tests/test_data/curated/attachments
  test_curated_notes: tests/test_data/curated/notes
  test_curated_vault: tests/test_data/curated
  test_preprocessed_attachments: tests/test_data/preprocessed/attachments
  test_preprocessed_notes: tests/test_data/preprocessed/notes
  test_preprocessed_vault: tests/test_data/preprocessed
  test_raw_attachments: tests/test_data/raw/attachments
  test_raw_notes: tests/test_data/raw/notes
  test_raw_vault: tests/test_data/raw
  vault: /Users/jose/Documents/Obsidian/Ever-preprocessed
priorities:
- pdf
- text
- image
summaries:
  image:
    bullets: 6
    max_tokens: 500
  pdf:
    bullets: 8
    max_tokens: 900
taxonomy:
  categories:
  - Infrastructure Investment
  - PPP/P3
  - Concessions
  - Project Finance
  - Risk Management
  - Roads & Transport
  - Water & Wastewater
  - Energy
  - Hospitals & Social Infrastructure
  - Railways
  - Digital Transformation
  - AI & Machine Learning
  - Digital Twins
  - Geospatial Data
  - Process Automation
  - Governance & Transparency
  - Policy & Regulation
  - Strategic Planning
  - Asset Management
  - Technical Due Diligence
  - Feasibility Studies
  - Market Intelligence
  - Critical Infrastructure Protection
  - Spain
  - Europe
  - LATAM
  - International Development
  - ESG & Sustainability
  - Climate Resilience
  - Innovation & R&D
  - Capacity Building
